services:
  - type: web
    name: security-camera-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 Sourcecode:app --bind 0.0.0.0:5000
    pythonVersion: 3.9
