services:
  - type: web
    name: security-camera-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python Sourcecode.py
    pythonVersion: 3.9  # or any version supported by Render, like 3.8, 3.10, etc.
